/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIdIndexRouteImport } from './routes/todos/$id/index'
import { Route as TodosCreateIndexRouteImport } from './routes/todos/create/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdIndexRoute = TodosIdIndexRouteImport.update({
  id: '/todos/$id/',
  path: '/todos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosCreateIndexRoute = TodosCreateIndexRouteImport.update({
  id: '/todos/create/',
  path: '/todos/create/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos/$id/': typeof TodosIdIndexRoute
  '/todos/create/': typeof TodosCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos/$id': typeof TodosIdIndexRoute
  '/todos/create': typeof TodosCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todos/$id/': typeof TodosIdIndexRoute
  '/todos/create/': typeof TodosCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos/$id/' | '/todos/create/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/$id' | '/todos/create'
  id: '__root__' | '/' | '/todos/$id/' | '/todos/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosIdIndexRoute: typeof TodosIdIndexRoute
  TodosCreateIndexRoute: typeof TodosCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id/': {
      id: '/todos/$id/'
      path: '/todos/$id'
      fullPath: '/todos/$id/'
      preLoaderRoute: typeof TodosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/create/': {
      id: '/todos/create/'
      path: '/todos/create'
      fullPath: '/todos/create/'
      preLoaderRoute: typeof TodosCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosIdIndexRoute: TodosIdIndexRoute,
  TodosCreateIndexRoute: TodosCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
